FROM golang:1.20.3 AS builder
WORKDIR /app
ADD . .
RUN CGO_ENABLED=0 go build -v -o worker cmd/worker/*

FROM ubuntu
WORKDIR /app
RUN apt update && apt install -y --no-install-recommends iputils-ping && rm -rf /var/lib/apt/lists/*
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
EXPOSE 50051
ENTRYPOINT ["/tini", "--"]
CMD ["/app/worker"]
COPY --from=builder /app/worker ./
