FROM golang:1.20.3 AS backend-builder
WORKDIR /app
ADD . .
RUN ./build.sh server

FROM node:20 AS frontend-builder
WORKDIR /app
ADD . .
RUN cd frontend && yarn && yarn build

FROM ubuntu
WORKDIR /app
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
EXPOSE 8085
ENTRYPOINT ["/tini", "--"]
CMD ["/app/server"]
COPY --from=backend-builder /app/server ./
COPY --from=frontend-builder /app/frontend/build ./build
