FROM golang:1.20.4 AS builder
WORKDIR /app
ADD . .
RUN ./build.sh worker

FROM ubuntu
WORKDIR /app
RUN apt update && apt install -y --no-install-recommends iputils-ping traceroute && rm -rf /var/lib/apt/lists/*
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
EXPOSE 50051
ENTRYPOINT ["/tini", "--"]
CMD ["/app/worker"]
COPY --from=builder /app/dist/worker ./
