// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/mtrsb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_ANY  Protocol = 0
	Protocol_IPV4 Protocol = 1
	Protocol_IPV6 Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "ANY",
		1: "IPV4",
		2: "IPV6",
	}
	Protocol_value = map[string]int32{
		"ANY":  0,
		"IPV4": 1,
		"IPV6": 2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mtrsb_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_mtrsb_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Protocol Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=Protocol" json:"protocol,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mtrsb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PingRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_ANY
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*PingResponse_Reply
	//	*PingResponse_Timeout
	//	*PingResponse_Summary
	//	*PingResponse_Error
	//	*PingResponse_Lookup
	Response isPingResponse_Response `protobuf_oneof:"response"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mtrsb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{1}
}

func (m *PingResponse) GetResponse() isPingResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *PingResponse) GetReply() *PingReply {
	if x, ok := x.GetResponse().(*PingResponse_Reply); ok {
		return x.Reply
	}
	return nil
}

func (x *PingResponse) GetTimeout() *PingTimeout {
	if x, ok := x.GetResponse().(*PingResponse_Timeout); ok {
		return x.Timeout
	}
	return nil
}

func (x *PingResponse) GetSummary() *PingSummary {
	if x, ok := x.GetResponse().(*PingResponse_Summary); ok {
		return x.Summary
	}
	return nil
}

func (x *PingResponse) GetError() *Error {
	if x, ok := x.GetResponse().(*PingResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *PingResponse) GetLookup() *HostLookupResult {
	if x, ok := x.GetResponse().(*PingResponse_Lookup); ok {
		return x.Lookup
	}
	return nil
}

type isPingResponse_Response interface {
	isPingResponse_Response()
}

type PingResponse_Reply struct {
	Reply *PingReply `protobuf:"bytes,1,opt,name=reply,proto3,oneof"`
}

type PingResponse_Timeout struct {
	Timeout *PingTimeout `protobuf:"bytes,2,opt,name=timeout,proto3,oneof"`
}

type PingResponse_Summary struct {
	Summary *PingSummary `protobuf:"bytes,3,opt,name=summary,proto3,oneof"`
}

type PingResponse_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type PingResponse_Lookup struct {
	Lookup *HostLookupResult `protobuf:"bytes,5,opt,name=lookup,proto3,oneof"`
}

func (*PingResponse_Reply) isPingResponse_Response() {}

func (*PingResponse_Timeout) isPingResponse_Response() {}

func (*PingResponse_Summary) isPingResponse_Response() {}

func (*PingResponse_Error) isPingResponse_Response() {}

func (*PingResponse_Lookup) isPingResponse_Response() {}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rtt   float32 `protobuf:"fixed32,1,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Ttl   int32   `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Seq   int32   `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Bytes int32   `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mtrsb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{2}
}

func (x *PingReply) GetRtt() float32 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

func (x *PingReply) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *PingReply) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PingReply) GetBytes() int32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type PingTimeout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq int32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *PingTimeout) Reset() {
	*x = PingTimeout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mtrsb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingTimeout) ProtoMessage() {}

func (x *PingTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingTimeout.ProtoReflect.Descriptor instead.
func (*PingTimeout) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{3}
}

func (x *PingTimeout) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PingSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sent     int32 `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Received int32 `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
}

func (x *PingSummary) Reset() {
	*x = PingSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mtrsb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingSummary) ProtoMessage() {}

func (x *PingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingSummary.ProtoReflect.Descriptor instead.
func (*PingSummary) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{4}
}

func (x *PingSummary) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *PingSummary) GetReceived() int32 {
	if x != nil {
		return x.Received
	}
	return 0
}

type HostLookupResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *HostLookupResult) Reset() {
	*x = HostLookupResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mtrsb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostLookupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostLookupResult) ProtoMessage() {}

func (x *HostLookupResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostLookupResult.ProtoReflect.Descriptor instead.
func (*HostLookupResult) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{5}
}

func (x *HostLookupResult) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mtrsb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_proto_mtrsb_proto protoreflect.FileDescriptor

var file_proto_mtrsb_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x74, 0x72, 0x73, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xdf, 0x01,
	0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x28, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x48, 0x00, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x07, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x57, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x74, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x74, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x3d, 0x0a, 0x0b, 0x50, 0x69, 0x6e,
	0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x48, 0x6f, 0x73, 0x74,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x37, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x2a, 0x27, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x50,
	0x56, 0x34, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x50, 0x56, 0x36, 0x10, 0x02, 0x32, 0x34,
	0x0a, 0x0b, 0x4d, 0x74, 0x72, 0x53, 0x62, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x25, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0c, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mtrsb_proto_rawDescOnce sync.Once
	file_proto_mtrsb_proto_rawDescData = file_proto_mtrsb_proto_rawDesc
)

func file_proto_mtrsb_proto_rawDescGZIP() []byte {
	file_proto_mtrsb_proto_rawDescOnce.Do(func() {
		file_proto_mtrsb_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mtrsb_proto_rawDescData)
	})
	return file_proto_mtrsb_proto_rawDescData
}

var file_proto_mtrsb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mtrsb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_mtrsb_proto_goTypes = []interface{}{
	(Protocol)(0),            // 0: Protocol
	(*PingRequest)(nil),      // 1: PingRequest
	(*PingResponse)(nil),     // 2: PingResponse
	(*PingReply)(nil),        // 3: PingReply
	(*PingTimeout)(nil),      // 4: PingTimeout
	(*PingSummary)(nil),      // 5: PingSummary
	(*HostLookupResult)(nil), // 6: HostLookupResult
	(*Error)(nil),            // 7: Error
}
var file_proto_mtrsb_proto_depIdxs = []int32{
	0, // 0: PingRequest.protocol:type_name -> Protocol
	3, // 1: PingResponse.reply:type_name -> PingReply
	4, // 2: PingResponse.timeout:type_name -> PingTimeout
	5, // 3: PingResponse.summary:type_name -> PingSummary
	7, // 4: PingResponse.error:type_name -> Error
	6, // 5: PingResponse.lookup:type_name -> HostLookupResult
	1, // 6: MtrSbWorker.Ping:input_type -> PingRequest
	2, // 7: MtrSbWorker.Ping:output_type -> PingResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_mtrsb_proto_init() }
func file_proto_mtrsb_proto_init() {
	if File_proto_mtrsb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mtrsb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mtrsb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mtrsb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mtrsb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingTimeout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mtrsb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mtrsb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostLookupResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mtrsb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_mtrsb_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PingResponse_Reply)(nil),
		(*PingResponse_Timeout)(nil),
		(*PingResponse_Summary)(nil),
		(*PingResponse_Error)(nil),
		(*PingResponse_Lookup)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mtrsb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mtrsb_proto_goTypes,
		DependencyIndexes: file_proto_mtrsb_proto_depIdxs,
		EnumInfos:         file_proto_mtrsb_proto_enumTypes,
		MessageInfos:      file_proto_mtrsb_proto_msgTypes,
	}.Build()
	File_proto_mtrsb_proto = out.File
	file_proto_mtrsb_proto_rawDesc = nil
	file_proto_mtrsb_proto_goTypes = nil
	file_proto_mtrsb_proto_depIdxs = nil
}
