// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/mtrsb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MtrSbWorkerClient is the client API for MtrSbWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MtrSbWorkerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (MtrSbWorker_PingClient, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type mtrSbWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewMtrSbWorkerClient(cc grpc.ClientConnInterface) MtrSbWorkerClient {
	return &mtrSbWorkerClient{cc}
}

func (c *mtrSbWorkerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (MtrSbWorker_PingClient, error) {
	stream, err := c.cc.NewStream(ctx, &MtrSbWorker_ServiceDesc.Streams[0], "/MtrSbWorker/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &mtrSbWorkerPingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MtrSbWorker_PingClient interface {
	Recv() (*PingResponse, error)
	grpc.ClientStream
}

type mtrSbWorkerPingClient struct {
	grpc.ClientStream
}

func (x *mtrSbWorkerPingClient) Recv() (*PingResponse, error) {
	m := new(PingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mtrSbWorkerClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/MtrSbWorker/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MtrSbWorkerServer is the server API for MtrSbWorker service.
// All implementations must embed UnimplementedMtrSbWorkerServer
// for forward compatibility
type MtrSbWorkerServer interface {
	Ping(*PingRequest, MtrSbWorker_PingServer) error
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedMtrSbWorkerServer()
}

// UnimplementedMtrSbWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedMtrSbWorkerServer struct {
}

func (UnimplementedMtrSbWorkerServer) Ping(*PingRequest, MtrSbWorker_PingServer) error {
	return status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMtrSbWorkerServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedMtrSbWorkerServer) mustEmbedUnimplementedMtrSbWorkerServer() {}

// UnsafeMtrSbWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MtrSbWorkerServer will
// result in compilation errors.
type UnsafeMtrSbWorkerServer interface {
	mustEmbedUnimplementedMtrSbWorkerServer()
}

func RegisterMtrSbWorkerServer(s grpc.ServiceRegistrar, srv MtrSbWorkerServer) {
	s.RegisterService(&MtrSbWorker_ServiceDesc, srv)
}

func _MtrSbWorker_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MtrSbWorkerServer).Ping(m, &mtrSbWorkerPingServer{stream})
}

type MtrSbWorker_PingServer interface {
	Send(*PingResponse) error
	grpc.ServerStream
}

type mtrSbWorkerPingServer struct {
	grpc.ServerStream
}

func (x *mtrSbWorkerPingServer) Send(m *PingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MtrSbWorker_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MtrSbWorkerServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MtrSbWorker/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MtrSbWorkerServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MtrSbWorker_ServiceDesc is the grpc.ServiceDesc for MtrSbWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MtrSbWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MtrSbWorker",
	HandlerType: (*MtrSbWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _MtrSbWorker_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _MtrSbWorker_Ping_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mtrsb.proto",
}
